### PR TITLE
Replacing removed update_attributes method

### LINKED ISSUE #612: Mark as read broken?
This weekend I upgraded my 2 year old stringer to the latest code, sadly this broke the "marked as read" in my reeder apps somehow. Not sure what happend there. Anyone else having the same issue?

### PR DESCRIPTION
**Pull request by bitboxer**
This will replace the method `update_attributes` that was removed in ActiveRecord 6.1. 

Fixes #612

### CODE REVIEW

File: app/commands/stories/mark_as_read.rb [hunk 1]
```diff
@@ -7,6 +7,6 @@ def initialize(story_id, repository = StoryRepository)
   end
 
   def mark_as_read
-    @repo.fetch(@story_id).update_attributes(is_read: true)
+    @repo.fetch(@story_id).update(is_read: true)
```
Comment (mockdeep) [inline app/commands/stories/mark_as_read.rb:10]: I think I might use `update!` for these so that it will fail loudly when it doesn't work for some reason.

File: spec/commands/stories/mark_as_read_spec.rb [hunk 2]
```diff
@@ -9,7 +9,7 @@
 
     it "marks a story as read" do
       command = MarkAsRead.new(1, repo)
-      expect(story).to receive(:update_attributes).with(is_read: true)
+      expect(story).to receive(:update).with(is_read: true)
```
Comment (mockdeep) [inline spec/commands/stories/mark_as_read_spec.rb:12]: This is one reason why I generally avoid stubbing methods. Does it work if we change it to something like:

```rb
expect { command.mark_as_read }.to change(story, :is_read).to(true)
```

**Review by mockdeep — COMMENTED** [review]
Thanks so much for fixing this!

File: spec/commands/stories/mark_as_read_spec.rb (hunk 2 above)
Comment (bitboxer) [reply spec/commands/stories/mark_as_read_spec.rb:12]: I would prefer that, too. But if you open the file you see that everything is stubbed out. I will change all files to actual model instances that hit the db.

File: app/commands/stories/mark_as_read.rb (hunk 1 above)
Comment (bitboxer) [reply app/commands/stories/mark_as_read.rb:10]: Yes, good idea.

**Comment by bitboxer** [comment]
@mockdeep I refactored the tests

**Comment by mockdeep** [comment]
Excellent, thank you!
